baseURL = "https://samarth1555.github.io/"
languageCode = "en-us"
title = "Samarth Keshari"
theme = "PaperMod"

[pagination]
  pagerSize = 10

enableRobotsTXT = true

[taxonomies]
  tag = "tags"
  category = "categories"

[[menu.main]]
  name = "Publications"
  url  = "/publications/"
  weight = 1

[[menu.main]]
  name = "Projects"
  url  = "/projects/"
  weight = 2

[[menu.main]]
  name = "About Me"
  url  = "/about/"
  weight = 3

[[menu.main]]
  name = "Blogs"
  url  = "/posts/"
  weight = 4

[[menu.main]]
  name = "Tags"
  url  = "/tags/"
  weight = 5

[params.profileMode]
  enabled = false
  title = "Samarth Keshari"
  subtitle = """B.Tech Undergraduate (2023–2027) | Developer | AI & Problem-Solving Enthusiast

Skilled in building real-world applications using web technologies, Java, and Flask, with a strong foundation in Data Structures & Algorithms.  
Interested in AI domains such as Model Interpretability, Agentic Systems, and Multimodal LLMs.

Passionate about developing scalable solutions, exploring innovative ideas, and solving real-world challenges through technology."""
  imageTitle = "Profile Photo"
  imageWidth = 200
  imageHeight = 200

[[params.profileMode.buttons]]
  name = "Publications"
  url  = "/publications/"
[[params.profileMode.buttons]]
  name = "Projects"
  url  = "/projects/"
[[params.profileMode.buttons]]
  name = "About Me"
  url  = "/about/"
[[params.profileMode.buttons]]
  name = "Blogs"
  url  = "/posts/"
[[params.profileMode.buttons]]
  name = "Tags"
  url  = "/tags/"

  
[[params.socialIcons]]
  name = "file-text"
  url  = "/Samarth_2026_Resume.pdf"

[[params.socialIcons]]
  name = "email"
  url  = "mailto:samarthkeshari15@gmail.com"

[[params.socialIcons]]
  name = "linkedin"
  url  = "https://www.linkedin.com/in/samarth-keshari-a13868354"

[[params.socialIcons]]
  name = "github"
  url  = "https://github.com/samarth1555"

[[params.socialIcons]]
  name = "huggingface"
  url  = "https://huggingface.co/Samarth15"

[[params.socialIcons]]
  name = "kaggle"
  url  = "https://www.kaggle.com/samarthkeshari"

[[params.socialIcons]]
  name = "discord"
  url  = "https://discord.gg/samarth00377"

[permalinks]
  posts = "/blog/:slug/"

[params]
  author = "Samarth Keshari"
  defaultTheme = "dark"
  env = "production"
